#[repr(C)]
struct CbtEventV0 {
    time: u64,
    src_agent: u64,
    dst_agent: u64,
    value: i32,
    buff_dmg: i32,
    overstack_value: u16,
    skillid: u16,
    src_instid: u16,
    dst_instid: u16,
    src_master_instid: u16,
    iss_offset: u8,
    iss_offset_target: u8,
    iss_bd_offset: u8,
    iss_bd_offset_target: u8,
    iss_alt_offset: u8,
    iss_alt_offset_target: u8,
    skar: u8,
    skar_alt: u8,
    skar_use_alt: u8,
    iff: u8,
    buff: u8,
    result: u8,
    is_activation: u8,
    is_buffremove: u8,
    is_ninety: u8,
    is_fifty: u8,
    is_moving: u8,
    is_statechange: u8,
    is_flanking: u8,
    is_shields: u8,
    is_offcycle: u8,
    pad64: u8,
}

struct CbtEventV1 {
    time: u64,
    src_agent: u64,
    dst_agent: u64,
    value: i32,
    buff_dmg: i32,
    overstack_value: u32,
    skillid: u32,
    src_instid: u16,
    dst_instid: u16,
    src_master_instid: u16,
    dst_master_instid: u16,
    iff: u8,
    buff: u8,
    result: u8,
    is_activation: u8,
    is_buffremove: u8,
    is_ninety: u8,
    is_fifty: u8,
    is_moving: u8,
    is_statechange: u8,
    is_flanking: u8,
    is_shields: u8,
    is_offcycle: u8,
    pad61: u8,
    pad62: u8,
    pad63: u8,
    pad64: u8,
}

fn main() {
    println!("Hello, world!");
}
